# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: analytics.proto for package ''

require 'grpc'
require 'analytics_pb'

module AnalyticsService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'AnalyticsService'

    rpc :PrimeSuspects, ::PrimeSuspectsRequest, ::PrimeSuspectsResponse
    rpc :MostActivePerson, ::Empty, ::MostActivePersonResponse
    rpc :TopDefaulter, ::Empty, ::TopDefaulterResponse
  end

  Stub = Service.rpc_stub_class
end
