# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto

require 'google/protobuf'


descriptor_data = "\n\x0f\x61nalytics.proto\"\x07\n\x05\x45mpty\"R\n\x14PrimeSuspectsRequest\x12\x14\n\x0c\x61partment_id\x18\x01 \x01(\x05\x12\x12\n\ncrime_from\x18\x02 \x01(\t\x12\x10\n\x08\x63rime_to\x18\x03 \x01(\t\"\x82\x01\n\x07Suspect\x12\x0c\n\x04rfid\x18\x01 \x01(\t\x12\x13\n\x0bperson_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nentered_at\x18\x04 \x01(\t\x12\x11\n\texited_at\x18\x05 \x01(\t\x12\x1f\n\x17\x64uration_inside_minutes\x18\x06 \x01(\x05\"f\n\x15PrimeSuspectsResponse\x12\x14\n\x0c\x61partment_id\x18\x01 \x01(\x05\x12\x15\n\rsuspect_count\x18\x02 \x01(\x05\x12 \n\x0eprime_suspects\x18\x03 \x03(\x0b\x32\x08.Suspect\"b\n\x18MostActivePersonResponse\x12\x0c\n\x04rfid\x18\x01 \x01(\t\x12\x13\n\x0bperson_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rtotal_entries\x18\x04 \x01(\x05\"(\n\x0cResidentInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"f\n\x14TopDefaulterResponse\x12\x14\n\x0c\x61partment_id\x18\x01 \x01(\x05\x12 \n\tresidents\x18\x02 \x03(\x0b\x32\r.ResidentInfo\x12\x16\n\x0etotal_defaults\x18\x03 \x01(\x05\x32\xb8\x01\n\x10\x41nalyticsService\x12>\n\rPrimeSuspects\x12\x15.PrimeSuspectsRequest\x1a\x16.PrimeSuspectsResponse\x12\x35\n\x10MostActivePerson\x12\x06.Empty\x1a\x19.MostActivePersonResponse\x12-\n\x0cTopDefaulter\x12\x06.Empty\x1a\x15.TopDefaulterResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
PrimeSuspectsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimeSuspectsRequest").msgclass
Suspect = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Suspect").msgclass
PrimeSuspectsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PrimeSuspectsResponse").msgclass
MostActivePersonResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MostActivePersonResponse").msgclass
ResidentInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ResidentInfo").msgclass
TopDefaulterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TopDefaulterResponse").msgclass
